const enumEvt = {
    BROADCAST_ENDMINING: 'BROADCASE_ENDMINING',
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
    ADD_NODE: 'ADD_NODE',
    PARSE_CHAIN: 'PARSE_CHAIN',
    START_MINING: 'START_MINING',
    END_MINING: 'END_MINING',
}

module.exports = enumEvt;